name: Nuitka - macOS 

on:
  workflow_dispatch:
    inputs:
      artemis_version:
        description: 'Version'
        required: true
        default: '4.1.0'
        type: string

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Build and package
        run: sh ./building/macOS/build_macos.sh
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Artemis-macOS-${{github.event.inputs.artemis_version}}
          path: app.app/**/*
          include-hidden-files: true
